// Generated by CIRCT firtool-1.75.0
module IBuf(	// @[generators/rocket-chip/src/main/scala/rocket/IBuf.scala:21:7]
  output        io_imem_ready,	// @[generators/rocket-chip/src/main/scala/rocket/IBuf.scala:22:14]
  input         io_imem_valid,	// @[generators/rocket-chip/src/main/scala/rocket/IBuf.scala:22:14]
  input  [31:0] io_imem_bits_pc,	// @[generators/rocket-chip/src/main/scala/rocket/IBuf.scala:22:14]
  input  [31:0] io_imem_bits_data,	// @[generators/rocket-chip/src/main/scala/rocket/IBuf.scala:22:14]
  input         io_imem_bits_xcpt_pf_inst,	// @[generators/rocket-chip/src/main/scala/rocket/IBuf.scala:22:14]
  input         io_imem_bits_xcpt_gf_inst,	// @[generators/rocket-chip/src/main/scala/rocket/IBuf.scala:22:14]
  input         io_imem_bits_xcpt_ae_inst,	// @[generators/rocket-chip/src/main/scala/rocket/IBuf.scala:22:14]
  input         io_imem_bits_replay,	// @[generators/rocket-chip/src/main/scala/rocket/IBuf.scala:22:14]
  output [31:0] io_pc,	// @[generators/rocket-chip/src/main/scala/rocket/IBuf.scala:22:14]
  input         io_inst_0_ready,	// @[generators/rocket-chip/src/main/scala/rocket/IBuf.scala:22:14]
  output        io_inst_0_valid,	// @[generators/rocket-chip/src/main/scala/rocket/IBuf.scala:22:14]
  output        io_inst_0_bits_xcpt0_pf_inst,	// @[generators/rocket-chip/src/main/scala/rocket/IBuf.scala:22:14]
  output        io_inst_0_bits_xcpt0_gf_inst,	// @[generators/rocket-chip/src/main/scala/rocket/IBuf.scala:22:14]
  output        io_inst_0_bits_xcpt0_ae_inst,	// @[generators/rocket-chip/src/main/scala/rocket/IBuf.scala:22:14]
  output        io_inst_0_bits_replay,	// @[generators/rocket-chip/src/main/scala/rocket/IBuf.scala:22:14]
  output [31:0] io_inst_0_bits_inst_bits,	// @[generators/rocket-chip/src/main/scala/rocket/IBuf.scala:22:14]
  output [4:0]  io_inst_0_bits_inst_rd,	// @[generators/rocket-chip/src/main/scala/rocket/IBuf.scala:22:14]
  output [4:0]  io_inst_0_bits_inst_rs1,	// @[generators/rocket-chip/src/main/scala/rocket/IBuf.scala:22:14]
  output [4:0]  io_inst_0_bits_inst_rs2,	// @[generators/rocket-chip/src/main/scala/rocket/IBuf.scala:22:14]
  output [31:0] io_inst_0_bits_raw	// @[generators/rocket-chip/src/main/scala/rocket/IBuf.scala:22:14]
);

  wire _valid_T_1 = ~io_imem_valid - 1'h1;	// @[generators/rocket-chip/src/main/scala/rocket/IBuf.scala:74:33]
  RVCExpander exp (	// @[generators/rocket-chip/src/main/scala/rocket/IBuf.scala:86:21]
    .io_in       (io_imem_bits_data),
    .io_out_bits (io_inst_0_bits_inst_bits),
    .io_out_rd   (io_inst_0_bits_inst_rd),
    .io_out_rs1  (io_inst_0_bits_inst_rs1),
    .io_out_rs2  (io_inst_0_bits_inst_rs2)
  );	// @[generators/rocket-chip/src/main/scala/rocket/IBuf.scala:86:21]
  assign io_imem_ready = io_inst_0_ready;	// @[generators/rocket-chip/src/main/scala/rocket/IBuf.scala:21:7]
  assign io_pc = io_imem_bits_pc;	// @[generators/rocket-chip/src/main/scala/rocket/IBuf.scala:21:7]
  assign io_inst_0_valid = _valid_T_1;	// @[generators/rocket-chip/src/main/scala/rocket/IBuf.scala:21:7, :74:33]
  assign io_inst_0_bits_xcpt0_pf_inst = io_imem_bits_xcpt_pf_inst;	// @[generators/rocket-chip/src/main/scala/rocket/IBuf.scala:21:7]
  assign io_inst_0_bits_xcpt0_gf_inst = io_imem_bits_xcpt_gf_inst;	// @[generators/rocket-chip/src/main/scala/rocket/IBuf.scala:21:7]
  assign io_inst_0_bits_xcpt0_ae_inst = io_imem_bits_xcpt_ae_inst;	// @[generators/rocket-chip/src/main/scala/rocket/IBuf.scala:21:7]
  assign io_inst_0_bits_replay = io_imem_bits_replay & _valid_T_1;	// @[generators/rocket-chip/src/main/scala/rocket/IBuf.scala:21:7, :74:33, :78:35]
  assign io_inst_0_bits_raw = io_imem_bits_data;	// @[generators/rocket-chip/src/main/scala/rocket/IBuf.scala:21:7]
endmodule

