# ===========================================================================
# Main flow configuration file
# LibreLane basic example project
#
# ===========================================================================

meta:
  version: 2
  flow: Classic
  substituting_steps:
    Magic.DRC: Null
    KLayout.DRC: Null

DESIGN_NAME: pm32
CLOCK_PERIOD: 25
CLOCK_NET: clk

VERILOG_FILES:
- dir::pm32.v
- dir::spm.v
