// Generated by CIRCT firtool-1.75.0
module RoundAnyRawFNToRecFN_ie6_is32_oe11_os53(	// @[generators/hardfloat/hardfloat/src/main/scala/RoundAnyRawFNToRecFN.scala:48:5]
  input         io_in_isZero,	// @[generators/hardfloat/hardfloat/src/main/scala/RoundAnyRawFNToRecFN.scala:58:16]
  input         io_in_sign,	// @[generators/hardfloat/hardfloat/src/main/scala/RoundAnyRawFNToRecFN.scala:58:16]
  input  [7:0]  io_in_sExp,	// @[generators/hardfloat/hardfloat/src/main/scala/RoundAnyRawFNToRecFN.scala:58:16]
  input  [32:0] io_in_sig,	// @[generators/hardfloat/hardfloat/src/main/scala/RoundAnyRawFNToRecFN.scala:58:16]
  output [64:0] io_out	// @[generators/hardfloat/hardfloat/src/main/scala/RoundAnyRawFNToRecFN.scala:58:16]
);

  assign io_out = {io_in_sign, {{4{io_in_sExp[7]}}, io_in_sExp} + 12'h7C0 & ~(io_in_isZero ? 12'hE00 : 12'h0), io_in_isZero ? 52'h0 : {io_in_sig[30:0], 21'h0}};	// @[generators/hardfloat/hardfloat/src/main/scala/RoundAnyRawFNToRecFN.scala:48:5, :104:25, :140:28, :252:24, :253:{14,18}, :280:12, :281:16, :286:33]
endmodule

