// Generated by CIRCT firtool-1.75.0
module RVCExpander(	// @[generators/rocket-chip/src/main/scala/rocket/RVC.scala:190:7]
  input  [31:0] io_in,	// @[generators/rocket-chip/src/main/scala/rocket/RVC.scala:191:14]
  output [31:0] io_out_bits,	// @[generators/rocket-chip/src/main/scala/rocket/RVC.scala:191:14]
  output [4:0]  io_out_rd,	// @[generators/rocket-chip/src/main/scala/rocket/RVC.scala:191:14]
  output [4:0]  io_out_rs1,	// @[generators/rocket-chip/src/main/scala/rocket/RVC.scala:191:14]
  output [4:0]  io_out_rs2,	// @[generators/rocket-chip/src/main/scala/rocket/RVC.scala:191:14]
  output [4:0]  io_out_rs3	// @[generators/rocket-chip/src/main/scala/rocket/RVC.scala:191:14]
);

  assign io_out_bits = io_in;	// @[generators/rocket-chip/src/main/scala/rocket/RVC.scala:190:7]
  assign io_out_rd = io_in[11:7];	// @[generators/rocket-chip/src/main/scala/rocket/RVC.scala:20:36, :190:7]
  assign io_out_rs1 = io_in[19:15];	// @[generators/rocket-chip/src/main/scala/rocket/RVC.scala:20:57, :190:7]
  assign io_out_rs2 = io_in[24:20];	// @[generators/rocket-chip/src/main/scala/rocket/RVC.scala:20:79, :190:7]
  assign io_out_rs3 = io_in[31:27];	// @[generators/rocket-chip/src/main/scala/rocket/RVC.scala:20:101, :190:7]
endmodule

