# ===========================================================================
# Main flow configuration file
# Alfonso Cortés - Inria AIO
# Based on https://github.com/mole99/greyhound-ihp by Leo Moser
#
# ===========================================================================

meta:
  version: 2
  flow: Classic
  substituting_steps:
    Checker.DisconnectedPins: null
    Magic.DRC: Null
    KLayout.DRC: Null

DESIGN_NAME: test
CLOCK_PERIOD: 25
CLOCK_NET: clk

LIB:
  nom_typ_1p20V_25C:
    - pdk_dir::libs.ref/sg13g2_stdcell/lib/sg13g2_stdcell_typ_1p20V_25C.lib
  nom_fast_1p32V_m40C: 
    - pdk_dir::libs.ref/sg13g2_stdcell/lib/sg13g2_stdcell_fast_1p32V_m40C.lib
  nom_slow_1p08V_125C:
    - pdk_dir::libs.ref/sg13g2_stdcell/lib/sg13g2_stdcell_slow_1p08V_125C.lib

VERILOG_DEFINES:
- FUNCTIONAL

VERILOG_FILES:
- dir::test.v

# Floorplanning
FP_SIZING: absolute
DIE_AREA:  [ 0.00, 0.00, 600.00, 850.00 ]
CORE_AREA: [ 50, 50, 550, 800 ]
IO_PIN_ORDER_CFG: dir::pin_order.cfg

# PDN
VDD_NETS:
- VDD
GND_NETS:
- VSS
PDN_CFG: dir::pdn.tcl

# SDC
PNR_SDC_FILE: dir::constraint.sdc
SIGNOFF_SDC_FILE: dir::constraint.sdc
FALLBACK_SDC: dir::constraint.sdc

#MAGIC_EXT_USE_GDS: false

#FP_OBSTRUCTIONS:
#- [110, 110, 347, 447]
#- [110, 450, 347, 787]
#PDN_OBSTRUCTIONS:
#- [TopMetal2, 110, 120, 200, 400]
#- [TopMetal1, 110, 120, 200, 400]
#ROUTING_OBSTRUCTIONS:
#- [TopMetal2, 110, 110, 340, 440]
#- [TopMetal1, 110, 110, 340, 440]
#- [Metal5, 110, 120, 210, 220]
#- [Metal4, 110, 110, 347, 447]
#- [Metal4, 110, 450, 347, 787]
#- [Metal3, 110, 110, 347, 447]
#- [Metal3, 110, 450, 347, 787]
#- [Metal2, 110, 110, 347, 447]
#- [Metal2, 110, 450, 347, 787]
#- [Metal1, 110, 110, 347, 447]
#- [Metal1, 110, 450, 347, 787]


MACROS:
  RM_IHPSG13_1P_1024x16_c2_bm_bist: 
    gds: 
      - pdk_dir::libs.ref/sg13g2_sram/gds/RM_IHPSG13_1P_1024x16_c2_bm_bist.gds
    lef:
      - pdk_dir::libs.ref/sg13g2_sram/lef/RM_IHPSG13_1P_1024x16_c2_bm_bist.lef 
    nl:
      - pdk_dir::libs.ref/sg13g2_sram/verilog/RM_IHPSG13_1P_1024x16_c2_bm_bist.v
    lib:
      "nom_typ_1p20V_25C":
        - pdk_dir::libs.ref/sg13g2_sram/lib/RM_IHPSG13_1P_1024x16_c2_bm_bist_typ_1p20V_25C.lib
      "nom_fast_1p32V_m40C":
        - pdk_dir::libs.ref/sg13g2_sram/lib/RM_IHPSG13_1P_1024x16_c2_bm_bist_fast_1p32V_m55C.lib
      "nom_slow_1p08V_125C":
        - pdk_dir::libs.ref/sg13g2_sram/lib/RM_IHPSG13_1P_1024x16_c2_bm_bist_slow_1p08V_125C.lib
    instances:
      memory.sram_0:
        location: [100, 50.00]
        orientation: S
      memory.sram_1:
        location: [100, 463.54]
        orientation: FN
        
PDN_MACRO_CONNECTIONS:
  - "memory.sram_0 VDD VSS VDD! VSS!"
  - "memory.sram_0 VDD VSS VDDARRAY! VSS!"
  - "memory.sram_1 VDD VSS VDD! VSS!"
  - "memory.sram_1 VDD VSS VDDARRAY! VSS!"
  
  
